In [124]:
import pandas as pd
import numpy as np
from sklearn.cluster import DBSCAN

In [187]:
#For now, I am dropping rows that have missing values, since DBSCAN only works when there are no NANs
people = people.dropna()
people

name                               roles  \
21493          ...-gal                          {'source'}   
1997                AN                          {'source'}   
14402               AN                          {'source'}   
13148         ARAD₂-mu                       {'recipient'}   
13151         ARAD₂-mu                       {'recipient'}   
2351          ARAD₂-mu                          {'source'}   
21516         ARAD₂-mu                       {'recipient'}   
21527         ARAD₂-mu                       {'recipient'}   
17669         ARAD₂-mu                          {'source'}   
18381         ARAD₂-mu                          {'source'}   
18375         ARAD₂-mu                          {'source'}   
14920         ARAD₂-mu                    {'intermediary'}   
4763          ARAD₂-mu                          {'source'}   
14453         ARAD₂-mu                          {'source'}   
7218    ARAD₂-{d}nanna                          {'source'}   
21532   ARAD₂-{d}nanna                    {'intermediary'}   
10700   ARAD₂-{d}nanna                          {'source'}   
17302   ARAD₂-{d}nanna                  {'representative'}   
18134   ARAD₂-{d}nanna                          {'source'}   
10248   ARAD₂-{d}nanna                    {'intermediary'}   
5079    ARAD₂-{d}nanna                    {'intermediary'}   
17421   ARAD₂-{d}nanna                          {'source'}   
22538               AŠ                          {'source'}   
22043               IŠ                  {'representative'}   
9662              KU-x                          {'source'}   
9503        a-a-dingir                          {'source'}   
5094     a-a-dingir-mu                    {'intermediary'}   
5097     a-a-dingir-mu                    {'intermediary'}   
11897       a-a-kal-la                  {'representative'}   
12837       a-a-kal-la                    {'intermediary'}   
...                ...                                 ...   
17809   šu-{d}iš:ha-ra                    {'intermediary'}   
20962      šu-{d}iškur                    {'intermediary'}   
17994      šu-{d}iškur                    {'intermediary'}   
20960      šu-{d}iškur                       {'recipient'}   
17493      šu-{d}iškur                    {'intermediary'}   
14607  šu-{d}ma-mi-tum                          {'source'}   
10959  šu-{d}ma-mi-tum                    {'intermediary'}   
220    šu-{d}nin-šubur                          {'source'}   
15216  šu-{d}nin-šubur  {'representative', 'intermediary'}   
18892  šu-{d}nin-šubur                    {'intermediary'}   
5560        šu-{d}suen                    {'intermediary'}   
5768        šu-{d}suen                          {'source'}   
17537     šu-{d}šul-gi                    {'intermediary'}   
17346     šu-{d}šul-gi                    {'intermediary'}   
17907     šu-{d}šul-gi                    {'intermediary'}   
17554     šu-{d}šul-gi                    {'intermediary'}   
17795     šu-{d}šul-gi                    {'intermediary'}   
17977     šu-{d}šul-gi                    {'intermediary'}   
17803     šu-{d}šul-gi                    {'intermediary'}   
17812     šu-{d}šul-gi                    {'intermediary'}   
18243     šu-{d}šul-gi                    {'intermediary'}   
17956     šu-{d}šul-gi                    {'intermediary'}   
13197     šu-{d}šul-gi                    {'intermediary'}   
8198      šu-{d}šul-gi                    {'intermediary'}   
13206     šu-{d}šul-gi                    {'intermediary'}   
7437      šu-{d}šul-gi                    {'intermediary'}   
6147      šu-{d}šul-gi                    {'intermediary'}   
12901     šu-{d}šul-gi                    {'intermediary'}   
8221      šu-{d}šul-gi                          {'source'}   
6258      šu-{d}šul-gi                    {'intermediary'}   

                  profession  processed date              Archive  
21493                uš[die]         76.1208          dead animal  
1997                gu[cord]         

In [181]:
people = pd.read_csv("people_Drehem.csv")
archives = pd.read_csv("archive_map.csv")
archives['PID'] = [int(archives['PID'][i][1:]) for i in np.arange(len(archives['PID']))]
people = pd.merge(people, archives, how='inner', left_on='p index', right_on='PID')
people = people.drop(['PID', 'normalized name', 'family', 'date name', 'p index'], axis=1)
people = people.sort_values(['name'])

Our people dataframe contains columns for the variables we want to use on our clustering algorithm. Our next step is to convert our categorical data into numerical data. We can do this by creating a binary matrix. 

In [188]:
people_cat = people.select_dtypes(include=[object])
people_cat['profession'] = people_cat['profession'].astype(str)
people_cat['roles'] = people_cat['roles'].astype(str)
people_cat.head(3)

/Users/anjaliunnithan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/Users/anjaliunnithan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


name       roles   profession              Archive
21493  ...-gal  {'source'}      uš[die]          dead animal
1997        AN  {'source'}     gu[cord]          dead animal
14402       AN  {'source'}  guza[chair]  domesticated animal

In [189]:
# import preprocessing from sklearn
from sklearn import preprocessing

In [190]:
people_cat.columns

Index(['name', 'roles', 'profession', 'Archive'], dtype='object')

In [191]:
# TODO: create a LabelEncoder object and fit it to each feature in people_cat


# 1. INSTANTIATE
# encode labels with value between 0 and n_classes-1.
le = preprocessing.LabelEncoder()


# 2/3. FIT AND TRANSFORM
# use df.apply() to apply le.fit_transform to all columns
people_cat_2 = people_cat.apply(le.fit_transform)
people_cat_2

name  roles  profession  Archive
21493     0      9          85        0
1997      1      9          28        0
14402     1      9          31        1
13148     2      5          23        1
13151     2      5          23        1
2351      2      9          51        0
21516     2      5          72        1
21527     2      5          72        1
17669     2      9          51        1
18381     2      9          51        6
18375     2      9          51        4
14920     2      1          45        5
4763      2      9          51        1
14453     2      9          26        0
7218      3      9          71        3
21532     3      1          72        1
10700     3      9          71        0
17302     3      8          72        3
18134     3      9          72        6
10248     3      1          61        1
5079      3      1          94        1
17421     3      9          72        5
22538     4      9          84        1
22043     5      8          76        1
9662      6      9          14        1
9503      7      9          12        5
5094      8      1          94        4
5097      8      1          94        1
11897     9      8          54        1
12837     9      1          54        1
...     ...    ...         ...      ...
17809   531      1          47        1
20962   532      1          68        1
17994   532      1          68        1
20960   532      5          68        0
17493   532      1          68        1
14607   533      9          34        0
10959   533      1          34        1
220     534      9          68        1
15216   534      6          71        1
18892   534      1          52        1
5560    535      1          94        1
5768    535      9          94        1
17537   536      1          71        1
17346   536      1          71        1
17907   536      1          71        1
17554   536      1          71        1
17795   536      1          71        1
17977   536      1          71        1
17803   536      1          71        1
17812   536      1          71        1
18243   536      1          71        1
17956   536      1          71        1
13197   536      1          71        1
8198    536      1         103        2
13206   536      1          71        1
7437    536      1          71        1
6147    536      1          71        4
12901   536      1          71        1
8221    536      9         103        5
6258    536      1          71        1

[2292 rows x 4 columns]

In [192]:
# TODO: create a OneHotEncoder object, and fit it to all of people_cat

# 1. INSTANTIATE
enc = preprocessing.OneHotEncoder()

# 2. FIT
enc.fit(people_cat_2)

# 3. Transform
onehotlabels = enc.transform(people_cat_2).toarray()
onehotlabels.shape

# as you can see, you've the same number of rows 891
# but now you've so many more columns due to how we changed all the categorical data into numerical data

(2292, 659)

In [193]:
onehotlabels

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

We just converted our categorical data into a sparse matrix. We should add this matrix to our quantitative data. 

In [194]:
dates = [[people['processed date'].values[i]] for i in np.arange(len(people['processed date']))]
people_cat_quant = np.hstack((onehotlabels, dates))
people_cat_quant

array([[ 1.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 76.1208],
       [ 0.    ,  1.    ,  0.    , ...,  0.    ,  0.    , 69.01  ],
       [ 0.    ,  1.    ,  0.    , ...,  0.    ,  0.    , 68.1119],
       ...,
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 73.0816],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 83.0217],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 72.0409]])

Our matrix is now ready to be passed through the DBSCAN algorithm. 

Let's try the algorithm with the name "šu-{d}šul-gi"

In [208]:
people.loc[people['name'] == "šu-{d}šul-gi"]
name_example = people_cat_quant[people_cat_quant[:,536] == 1,:]

In [201]:
ni = {'name': people.groupby(['name']).size().keys()}
names_and_indices = pd.DataFrame(data=ni)
names_and_indices.head()

name
0         ...-gal
1              AN
2        ARAD₂-mu
3  ARAD₂-{d}nanna
4              AŠ

In [211]:
clustering = DBSCAN(eps=2).fit(name_example)
clustering.labels_

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0, -1,  0,  0, -1,
        0])