In [1]:
import pandas as pd
import numpy as np
import sys
# !{sys.executable} -m pip install sklearn
# !{sys.executable} -m pip install environment_kernels
# !{sys.executable} -m pip install msgpack
# !conda update --yes --prefix {sys.prefix} scikit-learn
# import preprocessing from sklearn
# from sklearn import preprocessing
from sklearn.cluster import DBSCAN
from sklearn.impute import SimpleImputer
from sklearn import preprocessing 

In [2]:
people = pd.read_csv("people_and_target.csv")
people = people.drop(['roles', 'normalized name', 'target norm_name','profession', 'family', 'Unnamed: 0', 'Unnamed: 0.1', 'p index', 'date name', 'source', 'target', "target's role"], axis = 1)
people

/Users/anjaliunnithan/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


name  processed date              Archive  \
0               a-bu-ni-ta         69.1000              unknown   
1               a-bu-ni-ta         69.1000              unknown   
2              du-u₂-du-ta         69.1000              unknown   
3            ur-ku₃-nun-na         85.0000              unknown   
4            ur-ku₃-nun-na         85.0000              unknown   
5            ur-ku₃-nun-na         85.0000  domesticated animal   
6            ur-ku₃-nun-na         85.0000  domesticated animal   
7            ur-ku₃-nun-na         85.0000  domesticated animal   
8            ur-ku₃-nun-na         85.0000  domesticated animal   
9            ur-ku₃-nun-na         85.0000  domesticated animal   
10           ur-ku₃-nun-na         85.0000  domesticated animal   
11           ur-ku₃-nun-na         85.0000  domesticated animal   
12           ur-ku₃-nun-na         85.0000  domesticated animal   
13           ur-ku₃-nun-na         85.0000  domesticated animal   
14           ur-ku₃-nun-na         85.0000  domesticated animal   
15           ur-ku₃-nun-na         85.0000  domesticated animal   
16           ur-ku₃-nun-na         85.0000  domesticated animal   
17            lu₂-{d}šara₂             NaN  domesticated animal   
18            lu₂-{d}šara₂             NaN  domesticated animal   
19            lu₂-{d}šara₂             NaN              unknown   
20            lu₂-{d}šara₂             NaN              unknown   
21              šeš-kal-la             NaN  domesticated animal   
22              šeš-kal-la             NaN  domesticated animal   
23              šeš-kal-la             NaN  domesticated animal   
24              šeš-kal-la             NaN  domesticated animal   
25              šeš-kal-la             NaN  domesticated animal   
26              šeš-kal-la             NaN  domesticated animal   
27              šeš-kal-la             NaN                queen   
28              šeš-kal-la             NaN                queen   
29              šeš-kal-la             NaN          dead animal   
...                    ...             ...                  ...   
53696          šu-ma-ma-ta         73.0100          dead animal   
53697     {d}šul-gi-a-a-mu         65.0403                queen   
53698     {d}šul-gi-a-a-mu         65.0403                queen   
53699  {d}šul-gi-si₂-im-ti         65.0403                queen   
53700     {d}šul-gi-iri-mu         67.1103  domesticated animal   
53701     {d}šul-gi-iri-mu         68.0125  domesticated animal   
53702     {d}šul-gi-iri-mu         68.0829  domesticated animal   
53703     {d}šul-gi-iri-mu         68.1005  domesticated animal   
53704     {d}šul-gi-a-a-mu         70.0907  domesticated animal   
53705     {d}šul-gi-a-a-mu         70.0907  domesticated animal   
53706     {d}šul-gi-a-a-mu         74.0102          dead animal   
53707     {d}šul-gi-iri-mu         55.0100                queen   
53708     {d}šul-gi-iri-mu         73.0116          dead animal   
53709     {d}šul-gi-iri-mu         73.0118          dead animal   
53710     {d}šul-gi-iri-mu         73.0125          dead animal   
53711     {d}šul-gi-iri-mu         73.0211          dead animal   
53712     {d}šul-gi-iri-mu         73.0419          dead animal   
53713     {d}šul-gi-iri-mu         73.0423          dead animal   
53714     {d}šul-gi-iri-mu         73.0702          dead animal   
53715     {d}šul-gi-iri-mu         73.0716          dead animal   
53716     {d}šul-gi-iri-mu         73.0911          dead animal   
53717     {d}šul-gi-iri-mu         73.1026          dead animal   
53718     {d}šul-gi-iri-mu         73.1114          dead animal   
53719     {d}šul-gi-iri-mu         73.1226          dead animal   
53720     {d}šul-gi-iri-mu         78.0313          dead animal   
53721     {d}šul-gi-iri-mu         78.0313          dead animal   
53722     {d}šul-gi-ra-še₃             NaN              unknown   
53723     {d}šul-gi-ra-še₃             NaN              unknown   
53

In [3]:
#For now, I am dropping rows that have missing values, since DBSCAN only works when there are no NANs
# people = people.dropna()

Our people dataframe contains columns for the variables we want to use on our clustering algorithm. Our next step is to convert our categorical data into numerical data. We can do this by creating a binary matrix. 

In [4]:
# people_cat = people.select_dtypes(include=[object])
# people_cat['profession'] = people_cat['profession'].astype(str)
# people_cat['roles'] = people_cat['roles'].astype(str)
# people_cat.head(3)

In [5]:
imp = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
lst = []
for n in people['name'].unique():
    x = people[people['name'] == n]
    flag = False
    for c in x.columns:
        if x[c].isnull().all():
            flag = True
            break
    if flag:
        continue
    lst.append(pd.DataFrame(imp.fit_transform(x)))

In [6]:
len(lst)

784

In [7]:
people_new = pd.DataFrame()
for i in lst:
    people_new = people_new.append(i)

In [8]:
people_new.columns = people.columns

In [9]:
people_new

name processed date              Archive  \
0                a-bu-ni-ta           69.1              unknown   
1                a-bu-ni-ta           69.1              unknown   
0               du-u₂-du-ta           69.1              unknown   
1               du-u₂-du-ta        81.1223          dead animal   
2               du-u₂-du-ta        81.1223          dead animal   
3               du-u₂-du-ta         80.033              unknown   
4               du-u₂-du-ta          70.03              unknown   
5               du-u₂-du-ta        81.1222  domesticated animal   
6               du-u₂-du-ta        81.0118              unknown   
7               du-u₂-du-ta        81.0118  domesticated animal   
8               du-u₂-du-ta        79.1128  domesticated animal   
9               du-u₂-du-ta          80.02          dead animal   
10              du-u₂-du-ta        80.0303          dead animal   
11              du-u₂-du-ta        80.0304          dead animal   
12              du-u₂-du-ta        80.0309          dead animal   
13              du-u₂-du-ta        80.0316          dead animal   
14              du-u₂-du-ta        80.0403          dead animal   
15              du-u₂-du-ta          80.05  domesticated animal   
16              du-u₂-du-ta        81.0118          dead animal   
17              du-u₂-du-ta        81.0118          dead animal   
18              du-u₂-du-ta        81.0118          dead animal   
19              du-u₂-du-ta        81.0118          dead animal   
20              du-u₂-du-ta        81.1106  domesticated animal   
21              du-u₂-du-ta        81.1106  domesticated animal   
22              du-u₂-du-ta        81.1226          dead animal   
0             ur-ku₃-nun-na             85              unknown   
1             ur-ku₃-nun-na             85              unknown   
2             ur-ku₃-nun-na             85  domesticated animal   
3             ur-ku₃-nun-na             85  domesticated animal   
4             ur-ku₃-nun-na             85  domesticated animal   
..                      ...            ...                  ...   
0         {d}en-lil₂-i₃-sa₆          51.04                queen   
0              ri-im-i₃-li₂          65.07                queen   
1              ri-im-i₃-li₂          65.07                queen   
0                    si-du₃          61.01  domesticated animal   
0             ur-eš₃-ku₃-ga          74.11  domesticated animal   
1             ur-eš₃-ku₃-ga          74.11  domesticated animal   
0        ta₂-lim-{d}en-lil₂        65.0808                queen   
1        ta₂-lim-{d}en-lil₂        65.0808                queen   
2        ta₂-lim-{d}en-lil₂        65.0808                queen   
3        ta₂-lim-{d}en-lil₂        65.0808                queen   
0           {d}nanna-mu-dah        61.0228  domesticated animal   
0             ur-tur-tur-ta             79              unknown   
0          ur-lugal-edin-na        62.0018                queen   
1          ur-lugal-edin-na        62.0018                queen   
0         ur-nigar{gar}-ke₄          64.05                queen   
0           {d}inanna-ka-ta          56.11              unknown   
1           {d}inanna-ka-ta          56.11              unknown   
0                  ur-x-nun          84.09  domesticated animal   
0            šu-eš₁₈-dar-ta        69.0221              unknown   
0           {d}šul-gi-zi-mu           64.1              unknown   
0                {d}igi-kur        65.1125                queen   
0         {d}nanna-ma-ba-ta          79.02          dead animal   
0           {d}nanna-ku₃-zu          81.05  domesticated animal   
1           {d}nanna-ku₃-zu          81.05  domesticated animal   
0                  uš-gi-na        73.0805          dead animal   
0                   ša₃-kal          70.03              unknown   
1                   ša₃-kal          70.03              unknown   
0      {d}be-la-at-suh₆-ner         65.092                queen   
0  

In [10]:
# TODO: create a LabelEncoder object and fit it to each feature in people_cat


# 1. INSTANTIATE
# encode labels with value between 0 and n_classes-1.
le = preprocessing.LabelEncoder()


# 2/3. FIT AND TRANSFORM
# use df.apply() to apply le.fit_transform to all columns
people_cat_2 = people_new.apply(le.fit_transform)
people_cat_2

name  processed date  Archive  target_name
0     44            1559        5          116
1     44            1559        5          652
0    201            1559        5          652
1    201            3503        0          451
2    201            3503        0          506
3    201            3433        5          176
4    201            1673        5          574
5    201            3502        1          224
6    201            3476        5          412
7    201            3476        1          412
8    201            3402        1          512
9    201            3418        0          773
10   201            3425        0          773
11   201            3426        0          517
12   201            3428        0          773
13   201            3429        0          773
14   201            3435        0          773
15   201            3444        1          412
16   201            3476        0          773
17   201            3476        0          773
18   201            3476        0          773
19   201            3476        0          773
20   201            3499        1          612
21   201            3499        1          625
22   201            3504        0          773
0    600            3708        5          520
1    600            3708        5          620
2    600            3708        1          520
3    600            3708        1          620
4    600            3708        1          520
..   ...             ...      ...          ...
0    705              36        4          791
0    561             768        4          790
1    561             768        4          832
0    569             184        1          691
0    595            2888        1          499
1    595            2888        1          499
0    581             790        4          617
1    581             790        4          617
2    581             790        4          617
3    581             790        4          617
0    722             195        1          802
0    623            3326        5          534
0    604             233        4          517
1    604             233        4          547
0    611             545        4          529
0    711              79        5          698
1    711              79        5          698
0    625            3682        1          825
0    774            1459        5          853
0    763             620        5          794
0    710             851        4          697
0    721            3331        0          718
0    718            3484        1          713
1    718            3484        1          713
0    672            2604        0          836
0    767            1673        5          805
1    767            1673        5          805
0    702             815        4          682
0    723             883        4          835
0    745            3718        1          775

[53243 rows x 4 columns]

In [11]:
# TODO: create a OneHotEncoder object, and fit it to all of people_cat

# 1. INSTANTIATE
enc = preprocessing.OneHotEncoder()

# 2. FIT
enc.fit(people_cat_2)

# 3. Transform
onehotlabels = enc.transform(people_cat_2).toarray()
onehotlabels.shape

# as you can see, you've the same number of rows 891
# but now you've so many more columns due to how we changed all the categorical data into numerical data

/Users/anjaliunnithan/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


(53243, 5430)

In [12]:
onehotlabels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

We just converted our categorical data into a sparse matrix. We should add this matrix to our quantitative data. 

In [13]:
dates = [[people_new['processed date'].values[i]] for i in np.arange(len(people_new['processed date']))]
people_cat_quant = np.hstack((onehotlabels, dates))
people_cat_quant

array([[ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 69.1   ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 69.1   ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 69.1   ],
       ...,
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 65.092 ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 66.021 ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 85.0323]])

Our matrix is now ready to be passed through the DBSCAN algorithm. 

Let's try the algorithm with the name "...-a"

In [14]:
people_new[people_new['name'] == 'du-u₂-du-ta']

name processed date              Archive       target_name
0   du-u₂-du-ta           69.1              unknown           za-la-a
1   du-u₂-du-ta        81.1223          dead animal    nu-ur₂-{d}suen
2   du-u₂-du-ta        81.1223          dead animal     ur-ku₃-nun-na
3   du-u₂-du-ta         80.033              unknown          hu-la-al
4   du-u₂-du-ta          70.03              unknown       ur-{d}nanše
5   du-u₂-du-ta        81.1222  domesticated animal     in-ta-e₃-a-ta
6   du-u₂-du-ta        81.0118              unknown            na-lu₅
7   du-u₂-du-ta        81.0118  domesticated animal            na-lu₅
8   du-u₂-du-ta        79.1128  domesticated animal          ur-me-me
9   du-u₂-du-ta          80.02          dead animal  {d}šul-gi-iri-mu
10  du-u₂-du-ta        80.0303          dead animal  {d}šul-gi-iri-mu
11  du-u₂-du-ta        80.0304          dead animal     ur-nigar{gar}
12  du-u₂-du-ta        80.0309          dead animal  {d}šul-gi-iri-mu
13  du-u₂-du-ta        80.0316          dead animal  {d}šul-gi-iri-mu
14  du-u₂-du-ta        80.0403          dead animal  {d}šul-gi-iri-mu
15  du-u₂-du-ta          80.05  domesticated animal            na-lu₅
16  du-u₂-du-ta        81.0118          dead animal  {d}šul-gi-iri-mu
17  du-u₂-du-ta        81.0118          dead animal  {d}šul-gi-iri-mu
18  du-u₂-du-ta        81.0118          dead animal  {d}šul-gi-iri-mu
19  du-u₂-du-ta        81.0118          dead animal  {d}šul-gi-iri-mu
20  du-u₂-du-ta        81.1106  domesticated animal  uri₅{ki}-ki-du₁₀
21  du-u₂-du-ta        81.1106  domesticated animal    u₂-na-ab-še-en
22  du-u₂-du-ta        81.1226          dead animal  {d}šul-gi-iri-mu

In [15]:
people_new.head()

name processed date      Archive     target_name
0   a-bu-ni-ta           69.1      unknown     du-u₂-du-ta
1   a-bu-ni-ta           69.1      unknown         za-la-a
0  du-u₂-du-ta           69.1      unknown         za-la-a
1  du-u₂-du-ta        81.1223  dead animal  nu-ur₂-{d}suen
2  du-u₂-du-ta        81.1223  dead animal   ur-ku₃-nun-na

In [16]:
# people.loc[people['name'] == "šu-{d}šul-gi"]
name_example = people_cat_quant[people_cat_quant[:,201] == 1,:]
name_example

array([[ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 69.1   ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 81.1223],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 81.1223],
       ...,
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 81.1106],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 81.1106],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 81.1226]])

In [17]:
ni = {'name': people.groupby(['name']).size().keys()}
names_and_indices = pd.DataFrame(data=ni)

In [18]:
clustering = DBSCAN(eps=2.5).fit(name_example)
clustering.labels_

array([-1,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0])

In [19]:
a = people_new.loc[people_new['name'] == "du-u₂-du-ta"]
a.reset_index()[pd.Series(clustering.labels_) == 0]

index         name processed date              Archive       target_name
1       1  du-u₂-du-ta        81.1223          dead animal    nu-ur₂-{d}suen
2       2  du-u₂-du-ta        81.1223          dead animal     ur-ku₃-nun-na
3       3  du-u₂-du-ta         80.033              unknown          hu-la-al
5       5  du-u₂-du-ta        81.1222  domesticated animal     in-ta-e₃-a-ta
6       6  du-u₂-du-ta        81.0118              unknown            na-lu₅
7       7  du-u₂-du-ta        81.0118  domesticated animal            na-lu₅
8       8  du-u₂-du-ta        79.1128  domesticated animal          ur-me-me
9       9  du-u₂-du-ta          80.02          dead animal  {d}šul-gi-iri-mu
10     10  du-u₂-du-ta        80.0303          dead animal  {d}šul-gi-iri-mu
11     11  du-u₂-du-ta        80.0304          dead animal     ur-nigar{gar}
12     12  du-u₂-du-ta        80.0309          dead animal  {d}šul-gi-iri-mu
13     13  du-u₂-du-ta        80.0316          dead animal  {d}šul-gi-iri-mu
14     14  du-u₂-du-ta        80.0403          dead animal  {d}šul-gi-iri-mu
15     15  du-u₂-du-ta          80.05  domesticated animal            na-lu₅
16     16  du-u₂-du-ta        81.0118          dead animal  {d}šul-gi-iri-mu
17     17  du-u₂-du-ta        81.0118          dead animal  {d}šul-gi-iri-mu
18     18  du-u₂-du-ta        81.0118          dead animal  {d}šul-gi-iri-mu
19     19  du-u₂-du-ta        81.0118          dead animal  {d}šul-gi-iri-mu
20     20  du-u₂-du-ta        81.1106  domesticated animal  uri₅{ki}-ki-du₁₀
21     21  du-u₂-du-ta        81.1106  domesticated animal    u₂-na-ab-še-en
22     22  du-u₂-du-ta        81.1226          dead animal  {d}šul-gi-iri-mu

In [20]:
a.reset_index()[pd.Series(clustering.labels_) == -1]

index         name processed date  Archive  target_name
0      0  du-u₂-du-ta           69.1  unknown      za-la-a
4      4  du-u₂-du-ta          70.03  unknown  ur-{d}nanše

In [21]:
people_cat_quant[(people_cat_quant[:,201] == 1) |(people_cat_quant[:,201] == 1) ,:]

array([[ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 69.1   ],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 81.1223],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 81.1223],
       ...,
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 81.1106],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 81.1106],
       [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 81.1226]])

In [22]:
people_new.head(180)
people_cat_quant[0:180]
# people_new.groupby('name')['processed date'].apply(list)
# people_new[people_new['name'] == 'ur-ku₃-nun-na']

array([[ 0. ,  0. ,  0. , ...,  0. ,  0. , 69.1],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. , 69.1],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. , 69.1],
       ...,
       [ 0. ,  0. ,  0. , ...,  0. ,  0. , 84.1],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. , 84.1],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. , 84.1]])

In [27]:
clustering = DBSCAN(eps=2.5).fit(people_cat_quant[0:200])
clustering.labels_

array([-1, -1, -1,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [28]:
people_new.head(180).reset_index()[pd.Series(clustering.labels_) == 0]

/Users/anjaliunnithan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


index         name processed date              Archive       target_name
3       1  du-u₂-du-ta        81.1223          dead animal    nu-ur₂-{d}suen
4       2  du-u₂-du-ta        81.1223          dead animal     ur-ku₃-nun-na
5       3  du-u₂-du-ta         80.033              unknown          hu-la-al
7       5  du-u₂-du-ta        81.1222  domesticated animal     in-ta-e₃-a-ta
8       6  du-u₂-du-ta        81.0118              unknown            na-lu₅
9       7  du-u₂-du-ta        81.0118  domesticated animal            na-lu₅
10      8  du-u₂-du-ta        79.1128  domesticated animal          ur-me-me
11      9  du-u₂-du-ta          80.02          dead animal  {d}šul-gi-iri-mu
12     10  du-u₂-du-ta        80.0303          dead animal  {d}šul-gi-iri-mu
13     11  du-u₂-du-ta        80.0304          dead animal     ur-nigar{gar}
14     12  du-u₂-du-ta        80.0309          dead animal  {d}šul-gi-iri-mu
15     13  du-u₂-du-ta        80.0316          dead animal  {d}šul-gi-iri-mu
16     14  du-u₂-du-ta        80.0403          dead animal  {d}šul-gi-iri-mu
17     15  du-u₂-du-ta          80.05  domesticated animal            na-lu₅
18     16  du-u₂-du-ta        81.0118          dead animal  {d}šul-gi-iri-mu
19     17  du-u₂-du-ta        81.0118          dead animal  {d}šul-gi-iri-mu
20     18  du-u₂-du-ta        81.0118          dead animal  {d}šul-gi-iri-mu
21     19  du-u₂-du-ta        81.0118          dead animal  {d}šul-gi-iri-mu
22     20  du-u₂-du-ta        81.1106  domesticated animal  uri₅{ki}-ki-du₁₀
23     21  du-u₂-du-ta        81.1106  domesticated animal    u₂-na-ab-še-en
24     22  du-u₂-du-ta        81.1226          dead animal  {d}šul-gi-iri-mu

In [29]:
people_new.head(180).reset_index()[pd.Series(clustering.labels_) == -1]

/Users/anjaliunnithan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


index         name processed date  Archive  target_name
0      0   a-bu-ni-ta           69.1  unknown  du-u₂-du-ta
1      1   a-bu-ni-ta           69.1  unknown      za-la-a
2      0  du-u₂-du-ta           69.1  unknown      za-la-a
6      4  du-u₂-du-ta          70.03  unknown  ur-{d}nanše

In [26]:
people_new.head(180).reset_index()[pd.Series(clustering.labels_) == 1]

index           name processed date              Archive  \
25       0  ur-ku₃-nun-na             85              unknown   
26       1  ur-ku₃-nun-na             85              unknown   
27       2  ur-ku₃-nun-na             85  domesticated animal   
28       3  ur-ku₃-nun-na             85  domesticated animal   
29       4  ur-ku₃-nun-na             85  domesticated animal   
30       5  ur-ku₃-nun-na             85  domesticated animal   
31       6  ur-ku₃-nun-na             85  domesticated animal   
32       7  ur-ku₃-nun-na             85  domesticated animal   
33       8  ur-ku₃-nun-na             85  domesticated animal   
34       9  ur-ku₃-nun-na             85  domesticated animal   
35      10  ur-ku₃-nun-na             85  domesticated animal   
36      11  ur-ku₃-nun-na             85  domesticated animal   
37      12  ur-ku₃-nun-na             85  domesticated animal   
38      13  ur-ku₃-nun-na             85  domesticated animal   
39      14  ur-ku₃-nun-na           84.1  domesticated animal   
40      15  ur-ku₃-nun-na           84.1  domesticated animal   
41      16  ur-ku₃-nun-na           84.1  domesticated animal   
42      17  ur-ku₃-nun-na           84.1  domesticated animal   
43      18  ur-ku₃-nun-na           84.1  domesticated animal   
44      19  ur-ku₃-nun-na           84.1  domesticated animal   
45      20  ur-ku₃-nun-na           84.1  domesticated animal   
46      21  ur-ku₃-nun-na           84.1  domesticated animal   
47      22  ur-ku₃-nun-na           84.1  domesticated animal   
48      23  ur-ku₃-nun-na           84.1  domesticated animal   
49      24  ur-ku₃-nun-na           84.1  domesticated animal   
50      25  ur-ku₃-nun-na           84.1  domesticated animal   
51      26  ur-ku₃-nun-na           84.1  domesticated animal   
52      27  ur-ku₃-nun-na           84.1  domesticated animal   
53      28  ur-ku₃-nun-na           84.1  domesticated animal   
54      29  ur-ku₃-nun-na           84.1  domesticated animal   
..     ...            ...            ...                  ...   
150    125  ur-ku₃-nun-na           84.1      precious object   
151    126  ur-ku₃-nun-na           84.1      precious object   
152    127  ur-ku₃-nun-na           84.1      precious object   
153    128  ur-ku₃-nun-na           84.1      precious object   
154    129  ur-ku₃-nun-na           84.1      precious object   
155    130  ur-ku₃-nun-na           84.1      precious object   
156    131  ur-ku₃-nun-na           84.1      precious object   
157    132  ur-ku₃-nun-na           84.1      precious object   
158    133  ur-ku₃-nun-na           84.1      precious object   
159    134  ur-ku₃-nun-na           84.1      precious object   
160    135  ur-ku₃-nun-na           84.1      precious object   
161    136  ur-ku₃-nun-na           84.1      precious object   
162    137  ur-ku₃-nun-na           84.1      precious object   
163    138  ur-ku₃-nun-na           84.1      precious object   
164    139  ur-ku₃-nun-na           84.1  domesticated animal   
165    140  ur-ku₃-nun-na           84.1  domesticated animal   
166    141  ur-ku₃-nun-na           84.1  domesticated animal   
167    142  ur-ku₃-nun-na           84.1  domesticated animal   
168    143  ur-ku₃-nun-na           84.1  domesticated animal   
169    144  ur-ku₃-nun-na           84.1  domesticated animal   
170    145  ur-ku₃-nun-na           84.1  domesticated animal   
171    146  ur-ku₃-nun-na           84.1  domesticated animal   
172    147  ur-ku₃-nun-na           84.1  domesticated animal   
173    148  ur-ku₃-nun-na           84.1  domesticated animal   
174    149  ur-ku₃-nun-na           84.1  domesticated animal   
175    150  ur-ku₃-nun-na           84.1  domesticated animal   
176    151  ur-ku₃-nun-na           84.1  domesticated animal   
177    152  ur-ku₃-nun-na           84.1  domesticated animal   
178    153  ur-ku₃-nun-na           84.1  domesticated animal   
179    154  ur-ku₃-nun-na           84.1

In [53]:
people_nodate = people_new.drop('processed date', axis = 1)
people_nodate.head()

name      Archive     target_name
0   a-bu-ni-ta      unknown     du-u₂-du-ta
1   a-bu-ni-ta      unknown         za-la-a
0  du-u₂-du-ta      unknown         za-la-a
1  du-u₂-du-ta  dead animal  nu-ur₂-{d}suen
2  du-u₂-du-ta  dead animal   ur-ku₃-nun-na

In [36]:
# TODO: create a LabelEncoder object and fit it to each feature in people_cat


# 1. INSTANTIATE
# encode labels with value between 0 and n_classes-1.
le2 = preprocessing.LabelEncoder()


# 2/3. FIT AND TRANSFORM
# use df.apply() to apply le.fit_transform to all columns
people_cat_3 = people_nodate.apply(le2.fit_transform)
people_cat_3

name  Archive  target_name
0     44        5          116
1     44        5          652
0    201        5          652
1    201        0          451
2    201        0          506
3    201        5          176
4    201        5          574
5    201        1          224
6    201        5          412
7    201        1          412
8    201        1          512
9    201        0          773
10   201        0          773
11   201        0          517
12   201        0          773
13   201        0          773
14   201        0          773
15   201        1          412
16   201        0          773
17   201        0          773
18   201        0          773
19   201        0          773
20   201        1          612
21   201        1          625
22   201        0          773
0    600        5          520
1    600        5          620
2    600        1          520
3    600        1          620
4    600        1          520
..   ...      ...          ...
0    705        4          791
0    561        4          790
1    561        4          832
0    569        1          691
0    595        1          499
1    595        1          499
0    581        4          617
1    581        4          617
2    581        4          617
3    581        4          617
0    722        1          802
0    623        5          534
0    604        4          517
1    604        4          547
0    611        4          529
0    711        5          698
1    711        5          698
0    625        1          825
0    774        5          853
0    763        5          794
0    710        4          697
0    721        0          718
0    718        1          713
1    718        1          713
0    672        0          836
0    767        5          805
1    767        5          805
0    702        4          682
0    723        4          835
0    745        1          775

[53243 rows x 3 columns]

In [37]:
# TODO: create a OneHotEncoder object, and fit it to all of people_cat

# 1. INSTANTIATE
enc2 = preprocessing.OneHotEncoder()

# 2. FIT
enc2.fit(people_cat_3)

# 3. Transform
onehotlabels2 = enc2.transform(people_cat_3).toarray()
onehotlabels2.shape

/Users/anjaliunnithan/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


(53243, 1653)

In [47]:
onehotlabels2
name_example2 = onehotlabels[onehotlabels2[:,201] == 1,:]
name_example2

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [51]:
clustering3 = DBSCAN(eps=2).fit(name_example2)
clustering3.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [52]:
a = people_nodate.loc[people_nodate['name'] == "du-u₂-du-ta"]
a.reset_index()[pd.Series(clustering3.labels_) == 0]

index         name              Archive       target_name
0       0  du-u₂-du-ta              unknown           za-la-a
1       1  du-u₂-du-ta          dead animal    nu-ur₂-{d}suen
2       2  du-u₂-du-ta          dead animal     ur-ku₃-nun-na
3       3  du-u₂-du-ta              unknown          hu-la-al
4       4  du-u₂-du-ta              unknown       ur-{d}nanše
5       5  du-u₂-du-ta  domesticated animal     in-ta-e₃-a-ta
6       6  du-u₂-du-ta              unknown            na-lu₅
7       7  du-u₂-du-ta  domesticated animal            na-lu₅
8       8  du-u₂-du-ta  domesticated animal          ur-me-me
9       9  du-u₂-du-ta          dead animal  {d}šul-gi-iri-mu
10     10  du-u₂-du-ta          dead animal  {d}šul-gi-iri-mu
11     11  du-u₂-du-ta          dead animal     ur-nigar{gar}
12     12  du-u₂-du-ta          dead animal  {d}šul-gi-iri-mu
13     13  du-u₂-du-ta          dead animal  {d}šul-gi-iri-mu
14     14  du-u₂-du-ta          dead animal  {d}šul-gi-iri-mu
15     15  du-u₂-du-ta  domesticated animal            na-lu₅
16     16  du-u₂-du-ta          dead animal  {d}šul-gi-iri-mu
17     17  du-u₂-du-ta          dead animal  {d}šul-gi-iri-mu
18     18  du-u₂-du-ta          dead animal  {d}šul-gi-iri-mu
19     19  du-u₂-du-ta          dead animal  {d}šul-gi-iri-mu
20     20  du-u₂-du-ta  domesticated animal  uri₅{ki}-ki-du₁₀
21     21  du-u₂-du-ta  domesticated animal    u₂-na-ab-še-en
22     22  du-u₂-du-ta          dead animal  {d}šul-gi-iri-mu

In [54]:
people_notarget = people_new.drop('target_name', axis = 1)
people_notarget.head()

name processed date      Archive
0   a-bu-ni-ta           69.1      unknown
1   a-bu-ni-ta           69.1      unknown
0  du-u₂-du-ta           69.1      unknown
1  du-u₂-du-ta        81.1223  dead animal
2  du-u₂-du-ta        81.1223  dead animal

In [55]:
# TODO: create a LabelEncoder object and fit it to each feature in people_cat


# 1. INSTANTIATE
# encode labels with value between 0 and n_classes-1.
le3 = preprocessing.LabelEncoder()

# 2/3. FIT AND TRANSFORM
# use df.apply() to apply le.fit_transform to all columns
people_cat_4 = people_notarget.apply(le3.fit_transform)
people_cat_4

name  processed date  Archive
0     44            1559        5
1     44            1559        5
0    201            1559        5
1    201            3503        0
2    201            3503        0
3    201            3433        5
4    201            1673        5
5    201            3502        1
6    201            3476        5
7    201            3476        1
8    201            3402        1
9    201            3418        0
10   201            3425        0
11   201            3426        0
12   201            3428        0
13   201            3429        0
14   201            3435        0
15   201            3444        1
16   201            3476        0
17   201            3476        0
18   201            3476        0
19   201            3476        0
20   201            3499        1
21   201            3499        1
22   201            3504        0
0    600            3708        5
1    600            3708        5
2    600            3708        1
3    600            3708        1
4    600            3708        1
..   ...             ...      ...
0    705              36        4
0    561             768        4
1    561             768        4
0    569             184        1
0    595            2888        1
1    595            2888        1
0    581             790        4
1    581             790        4
2    581             790        4
3    581             790        4
0    722             195        1
0    623            3326        5
0    604             233        4
1    604             233        4
0    611             545        4
0    711              79        5
1    711              79        5
0    625            3682        1
0    774            1459        5
0    763             620        5
0    710             851        4
0    721            3331        0
0    718            3484        1
1    718            3484        1
0    672            2604        0
0    767            1673        5
1    767            1673        5
0    702             815        4
0    723             883        4
0    745            3718        1

[53243 rows x 3 columns]

In [56]:
# TODO: create a OneHotEncoder object, and fit it to all of people_cat

# 1. INSTANTIATE
enc3 = preprocessing.OneHotEncoder()

# 2. FIT
enc3.fit(people_cat_4)

# 3. Transform
onehotlabels3 = enc3.transform(people_cat_4).toarray()
onehotlabels3.shape

onehotlabels3


/Users/anjaliunnithan/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [57]:
name_example3 = onehotlabels3[onehotlabels3[:,201] == 1,:]
name_example3

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [64]:
clustering4 = DBSCAN(eps=2.5).fit(name_example3)
clustering4.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [65]:
a = people_notarget.loc[people_notarget['name'] == "du-u₂-du-ta"]
a.reset_index()[pd.Series(clustering4.labels_) == 0]

index         name processed date              Archive
0       0  du-u₂-du-ta           69.1              unknown
1       1  du-u₂-du-ta        81.1223          dead animal
2       2  du-u₂-du-ta        81.1223          dead animal
3       3  du-u₂-du-ta         80.033              unknown
4       4  du-u₂-du-ta          70.03              unknown
5       5  du-u₂-du-ta        81.1222  domesticated animal
6       6  du-u₂-du-ta        81.0118              unknown
7       7  du-u₂-du-ta        81.0118  domesticated animal
8       8  du-u₂-du-ta        79.1128  domesticated animal
9       9  du-u₂-du-ta          80.02          dead animal
10     10  du-u₂-du-ta        80.0303          dead animal
11     11  du-u₂-du-ta        80.0304          dead animal
12     12  du-u₂-du-ta        80.0309          dead animal
13     13  du-u₂-du-ta        80.0316          dead animal
14     14  du-u₂-du-ta        80.0403          dead animal
15     15  du-u₂-du-ta          80.05  domesticated animal
16     16  du-u₂-du-ta        81.0118          dead animal
17     17  du-u₂-du-ta        81.0118          dead animal
18     18  du-u₂-du-ta        81.0118          dead animal
19     19  du-u₂-du-ta        81.0118          dead animal
20     20  du-u₂-du-ta        81.1106  domesticated animal
21     21  du-u₂-du-ta        81.1106  domesticated animal
22     22  du-u₂-du-ta        81.1226          dead animal

In [77]:
people_noarchive = people_new.drop('Archive', axis = 1)
people_noarchive.head()

# TODO: create a LabelEncoder object and fit it to each feature in people_cat


# # 1. INSTANTIATE
# # encode labels with value between 0 and n_classes-1.
le4 = preprocessing.LabelEncoder()


# # 2/3. FIT AND TRANSFORM
# # use df.apply() to apply le.fit_transform to all columns
people_cat_5 = people_noarchive.apply(le4.fit_transform)


# # TODO: create a OneHotEncoder object, and fit it to all of people_cat

# # 1. INSTANTIATE
enc4 = preprocessing.OneHotEncoder()

# # 2. FIT
enc4.fit(people_cat_5)

# # 3. Transform
onehotlabels4 = enc4.transform(people_cat_5).toarray()

name_example6 = onehotlabels4[onehotlabels4[:,201] == 1,:]

clustering5 = DBSCAN(eps=2).fit(name_example6)
clustering5.labels_

a = people_noarchive.loc[people_noarchive['name'] == "du-u₂-du-ta"]
a.reset_index()[pd.Series(clustering5.labels_) == 0]

/Users/anjaliunnithan/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


index         name processed date       target_name
0       0  du-u₂-du-ta           69.1           za-la-a
1       1  du-u₂-du-ta        81.1223    nu-ur₂-{d}suen
2       2  du-u₂-du-ta        81.1223     ur-ku₃-nun-na
3       3  du-u₂-du-ta         80.033          hu-la-al
4       4  du-u₂-du-ta          70.03       ur-{d}nanše
5       5  du-u₂-du-ta        81.1222     in-ta-e₃-a-ta
6       6  du-u₂-du-ta        81.0118            na-lu₅
7       7  du-u₂-du-ta        81.0118            na-lu₅
8       8  du-u₂-du-ta        79.1128          ur-me-me
9       9  du-u₂-du-ta          80.02  {d}šul-gi-iri-mu
10     10  du-u₂-du-ta        80.0303  {d}šul-gi-iri-mu
11     11  du-u₂-du-ta        80.0304     ur-nigar{gar}
12     12  du-u₂-du-ta        80.0309  {d}šul-gi-iri-mu
13     13  du-u₂-du-ta        80.0316  {d}šul-gi-iri-mu
14     14  du-u₂-du-ta        80.0403  {d}šul-gi-iri-mu
15     15  du-u₂-du-ta          80.05            na-lu₅
16     16  du-u₂-du-ta        81.0118  {d}šul-gi-iri-mu
17     17  du-u₂-du-ta        81.0118  {d}šul-gi-iri-mu
18     18  du-u₂-du-ta        81.0118  {d}šul-gi-iri-mu
19     19  du-u₂-du-ta        81.0118  {d}šul-gi-iri-mu
20     20  du-u₂-du-ta        81.1106  uri₅{ki}-ki-du₁₀
21     21  du-u₂-du-ta        81.1106    u₂-na-ab-še-en
22     22  du-u₂-du-ta        81.1226  {d}šul-gi-iri-mu